export const sameCharEn = [
  'A',
  'a',
  'B',
  'C',
  'c',
  'E',
  'e',
  'H',
  'K',
  'k',
  'M',
  'O',
  'o',
  'P',
  'p',
  'T',
  'X',
  'x',
  'y',
];
export const sameCharRu = [
  'А',
  'а',
  'В',
  'С',
  'с',
  'Е',
  'е',
  'Н',
  'К',
  'к',
  'М',
  'О',
  'о',
  'Р',
  'р',
  'Т',
  'Х',
  'х',
  'у',
];

export const colOrderObj = {
  opt1: [
    'numTiShem60',
    'kodTi60',
    'naimTi60',
    'tipSch60',
    'kanaly60',
    'tiAiis',
    'gr',
    'numTiSop',
    'naimTiSop',
    'numSchSop',
    'tipSchSop',
    'kttSop',
    'ktnSop',
    'kodTi80',
    'naimTi80',
    'tipSch80',
    'kanaly80',
    'naimTi82',
    'numSchSch',
    'tipSchSch',
    'tipSchDB',
    'numSchDB',
    'kttDB',
    'ktnDB',
  ],
  opt2: [
    'numTiShem60',
    'naimTi60',
    'naimTiSop',
    'naimTi80',
    'naimTi82',
    'tipSch60',
    'tipSchSop',
    'tipSch80',
    'tipSchSch',
    'tipSchDB',
    'tiAiis',
    'gr',
    'numTiSop',
    'numSchDB',
    'numSchSop',
    'numSchSch',
    'kttSop',
    'kttDB',
    'ktnSop',
    'ktnDB',
    'kodTi60',
    'kodTi80',
    'kanaly80',
    'kanaly60',
  ],
};
export const colFullName = {
  numTiShem60: '№ТИСх60',
  kodTi60: 'кодТИ60',
  naimTi60: '_______наимТИ60_______',
  tipSch60: 'типСч60',
  kanaly60: 'каналы60',
  tiAiis: 'ТИвАИИС',
  gr: '№ ГР',
  numTiSop: '№ТИСОП',
  naimTiSop: '___наим_ТИ_СОП___',
  naimTi80: '______наим_ТИ_80______',
  naimTi82: '___наим_ТИ_82___',
  numSchDB: '№ Сч ДБ',
  numSchSop: '№ Сч СОП',
  numSchSch: '№ СЧ Сч',
  tipSchSop: 'типСчСОП',
  tipSch80: 'типСч80',
  tipSchSch: 'типСчСч',
  tipSchDB: 'типСчДБ',
  kttSop: 'КттСОП',
  kttDB: 'КттДБ',
  ktnSop: 'КтнСОП',
  ktnDB: 'КтнДБ',
  kodTi80: 'кодТИ80',
  kanaly80: 'каналы80',
};
